####这个文件默认从classpath根目录或者当前目录加载
## 代码使用这个获取@Value(value = "${app.name}")
###注意后面的值有个空格
##可以对特定环境定义profile
#app:
 # name: myapp


server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0

  serviceUrl:
    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

